# Generated by Django 3.2.3 on 2021-05-25 01:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210524_2245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='remoteuser',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='remoteuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
