# Generated by Django 3.2.3 on 2021-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210524_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
